#define MCU_CLOCK_SOURCE
#define MCU_CLOCK_SOURCE_HXT
#define MCU_CLOCK_FREQUENCY     50000000

// // PWM0 for RGB LED
#define MCU_INTERFACE_PWM0
#define PWM0_CH01_CLOCK_SOURCE_HXT // HXT, LXT, HCLK, HIRC
#define PWM0_CH23_CLOCK_SOURCE_HXT // HXT, LXT, HCLK,
#define PIN_PWM0_CH0_PA12   // R
#define PIN_PWM0_CH1_PA13   // G
#define PIN_PWM0_CH2_PA14   // B
#define PIN_PWM0_CH3_PA15   // VCC

#define MCU_INTERFACE_ADC
#define ADC_CLOCK_SOURCE_HXT  // HXT, LXT, PLL, HIRC, HCLK
#define ADC_CLOCK_DIVIDER     1
#define PIN_ADC7_PA7
